name: cfv2-v1
on:
  workflow_dispatch:
  schedule:
    - cron: 0 4 * * *
    - cron: 0 10 * * *
    - cron: 0 16 * * *
    - cron: 0 22 * * *

jobs:
  env:
    runs-on: ubuntu-latest
    steps:
      - name: Set ENV
        run: |
          sudo apt update
          sudo apt -y install sshpass
          sudo passwd runner << EOD
          root
          root
          EOD
      - name: Set v2ray
        run: |
          mkdir v2ray
          cd v2ray
          wget https://github.com/v2fly/v2ray-core/releases/download/v5.0.6/v2ray-linux-64.zip
          unzip v2ray-linux-64.zip
          base64 -d > config.json << EOD
          ewoJImxvZyI6IHsKCQkibG9nbGV2ZWwiOiAiaW5mbyIKCX0sCgkiaW5ib3VuZHMiOiBbCgkJewoJ
          CQkicG9ydCI6IDM0NTYsCgkJCSJwcm90b2NvbCI6ICJ2bWVzcyIsCgkJCSJhbGxvY2F0ZSI6IHsK
          CQkJCSJzdHJhdGVneSI6ICJhbHdheXMiCgkJCX0sCgkJCSJzZXR0aW5ncyI6IHsKCQkJCSJjbGll
          bnRzIjogWwoJCQkJCXsKCQkJCQkJImlkIjogIjI2ZTNhNjIwLWUzM2UtNDVlNi1iMzE2LTQ1NzBi
          MGVjZjM5YyIsCgkJCQkJCSJsZXZlbCI6IDEsCgkJCQkJCSJhbHRlcklkIjogMCwKCQkJCQkJImVt
          YWlsIjogImNsaWVudEBleGFtcGxlLmNvbSIKCQkJCQl9CgkJCQldLAoJCQkJImRpc2FibGVJbnNl
          Y3VyZUVuY3J5cHRpb24iOiB0cnVlCgkJCX0sCgkJCSJzdHJlYW1TZXR0aW5ncyI6IHsKCQkJCSJu
          ZXR3b3JrIjogIndzIiwKCQkJCSJ3c1NldHRpbmdzIjogewoJCQkJCSJjb25uZWN0aW9uUmV1c2Ui
          OiB0cnVlLAoJCQkJCSJwYXRoIjogIi9ncmFwaHFsIgoJCQkJfSwKCQkJCSJzZWN1cml0eSI6ICJu
          b25lIiwKCQkJCSJ0Y3BTZXR0aW5ncyI6IHsKCQkJCQkiaGVhZGVyIjogewoJCQkJCQkidHlwZSI6
          ICJodHRwIiwKCQkJCQkJInJlc3BvbnNlIjogewoJCQkJCQkJInZlcnNpb24iOiAiMS4xIiwKCQkJ
          CQkJCSJzdGF0dXMiOiAiMjAwIiwKCQkJCQkJCSJyZWFzb24iOiAiT0siLAoJCQkJCQkJImhlYWRl
          cnMiOiB7CgkJCQkJCQkJIkNvbnRlbnQtVHlwZSI6IFsKCQkJCQkJCQkJImFwcGxpY2F0aW9uL29j
          dGV0LXN0cmVhbSIsCgkJCQkJCQkJCSJhcHBsaWNhdGlvbi94LW1zZG93bmxvYWQiLAoJCQkJCQkJ
          CQkidGV4dC9odG1sIiwKCQkJCQkJCQkJImFwcGxpY2F0aW9uL3gtc2hvY2t3YXZlLWZsYXNoIgoJ
          CQkJCQkJCV0sCgkJCQkJCQkJIlRyYW5zZmVyLUVuY29kaW5nIjogWwoJCQkJCQkJCQkiY2h1bmtl
          ZCIKCQkJCQkJCQldLAoJCQkJCQkJCSJDb25uZWN0aW9uIjogWwoJCQkJCQkJCQkia2VlcC1hbGl2
          ZSIKCQkJCQkJCQldLAoJCQkJCQkJCSJQcmFnbWEiOiAibm8tY2FjaGUiCgkJCQkJCQl9CgkJCQkJ
          CX0KCQkJCQl9CgkJCQl9CgkJCX0KCQl9CgldLAoJIm91dGJvdW5kcyI6IFsKCQl7CgkJCSJwcm90
          b2NvbCI6ICJmcmVlZG9tIiwKCQkJInNldHRpbmdzIjoge30KCQl9LAoJCXsKCQkJInByb3RvY29s
          IjogImJsYWNraG9sZSIsCgkJCSJzZXR0aW5ncyI6IHt9LAoJCQkidGFnIjogImJsb2NrZWQiCgkJ
          fQoJXSwKCSJyb3V0aW5nIjogewoJCSJkb21haW5TdHJhdGVneSI6ICJBc0lzIiwKCQkicnVsZXMi
          OiBbCgkJCXsKCQkJCSJ0eXBlIjogImZpZWxkIiwKCQkJCSJpcCI6IFsKCQkJCQkiMC4wLjAuMC84
          IiwKCQkJCQkiMTAuMC4wLjAvOCIsCgkJCQkJIjEwMC42NC4wLjAvMTAiLAoJCQkJCSIxMjcuMC4w
          LjAvOCIsCgkJCQkJIjE2OS4yNTQuMC4wLzE2IiwKCQkJCQkiMTcyLjE2LjAuMC8xMiIsCgkJCQkJ
          IjE5Mi4wLjAuMC8yNCIsCgkJCQkJIjE5Mi4wLjIuMC8yNCIsCgkJCQkJIjE5Mi4xNjguMC4wLzE2
          IiwKCQkJCQkiMTk4LjE4LjAuMC8xNSIsCgkJCQkJIjE5OC41MS4xMDAuMC8yNCIsCgkJCQkJIjIw
          My4wLjExMy4wLzI0IiwKCQkJCQkiOjoxLzEyOCIsCgkJCQkJImZjMDA6Oi83IiwKCQkJCQkiZmU4
          MDo6LzEwIiwKCQkJCQkiZ2VvaXA6cHJpdmF0ZSIKCQkJCV0sCgkJCQkib3V0Ym91bmRUYWciOiAi
          YmxvY2tlZCIKCQkJfSwKCQkJewoJCQkJInR5cGUiOiAiZmllbGQiLAoJCQkJInByb3RvY29sIjog
          WwoJCQkJCSJiaXR0b3JyZW50IgoJCQkJXSwKCQkJCSJvdXRib3VuZFRhZyI6ICJibG9ja2VkIgoJ
          CQl9CgkJXQoJfQp9
          EOD
          nohup ./v2ray run > v2ray.log &
          cd ~
      - name: c
        run: |
          sudo wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb && sudo dpkg -i cloudflared-linux-amd64.deb
          sysctl -w net.core.rmem_max=2500000
          base64 -d > config.yaml << EOD
          dHVubmVsOiBhNGM1YTY3MS0zNzI0LTRhNmUtYmVkYy02NGVhNzliMDIxMGEKY3JlZGVudGlhbHMtZmlsZTogYTRjNWE2NzEtMzcyNC00YTZlLWJlZGMtNjRlYTc5YjAyMTBhLmpzb24KaW5ncmVzczoKICAtIGhvc3RuYW1lOiB0ZXN0Mi4zMzY2LmdhCiAgICBwYXRoOiAvZ3JhcGhxbAogICAgc2VydmljZTogaHR0cDovL2xvY2FsaG9zdDozNDU2CiAgLSBob3N0bmFtZTogdGVzdDIuMzM2Ni5nYQogICAgc2VydmljZTogaHR0cDovL2xvY2FsaG9zdDo4MAogIC0gc2VydmljZTogaHR0cF9zdGF0dXM6NDA0
          EOD
          base64 -d > a4c5a671-3724-4a6e-bedc-64ea79b0210a.json << EOD
          eyJBY2NvdW50VGFnIjoiZTJiMjM3MGRiZGNmNjE4Y2JmN2EyMzI0ZDkzOGYxMDUiLCJUdW5uZWxTZWNyZXQiOiJyNDZiYStVdG85NHhBc1plOVV1ZmRCQTRRbVl3cTgzTTZ5LzZLNmd0TVFvPSIsIlR1bm5lbElEIjoiYTRjNWE2NzEtMzcyNC00YTZlLWJlZGMtNjRlYTc5YjAyMTBhIn0=
          EOD
          base64 -d > cert.pem << EOD
          LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR0hBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJHMHdhd0lCQVFRZ3V1cDQwV1FCMXBLQ211ZVgKWUV1bE82S2ErOU0rVmdhRytaK2hScm9RcE0raFJBTkNBQVI5aVhqRC8xUXA4WURjcnR1RFlYZG4rbXQxUEVJOAovdTlTajgvUk16TklsOVE5bFZJOW9sd2tSbGpySHlML0lZTjdZTEVuWlBIMHp2NDdtdWRoQWVOVgotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlER1RDQ0FzQ2dBd0lCQWdJVU1nNkh6RTEyVmFPSnlnN0xybUhROE5sZHNoUXdDZ1lJS29aSXpqMEVBd0l3CmdZOHhDekFKQmdOVkJBWVRBbFZUTVJNd0VRWURWUVFJRXdwRFlXeHBabTl5Ym1saE1SWXdGQVlEVlFRSEV3MVQKWVc0Z1JuSmhibU5wYzJOdk1Sa3dGd1lEVlFRS0V4QkRiRzkxWkVac1lYSmxMQ0JKYm1NdU1UZ3dOZ1lEVlFRTApFeTlEYkc5MVpFWnNZWEpsSUU5eWFXZHBiaUJUVTB3Z1JVTkRJRU5sY25ScFptbGpZWFJsSUVGMWRHaHZjbWwwCmVUQWVGdzB5TWpFeU1UTXdOVE0yTURCYUZ3MHpOekV5TURrd05UTTJNREJhTUdJeEdUQVhCZ05WQkFvVEVFTnMKYjNWa1JteGhjbVVzSUVsdVl5NHhIVEFiQmdOVkJBc1RGRU5zYjNWa1JteGhjbVVnVDNKcFoybHVJRU5CTVNZdwpKQVlEVlFRREV4MURiRzkxWkVac1lYSmxJRTl5YVdkcGJpQkRaWEowYVdacFkyRjBaVEJaTUJNR0J5cUdTTTQ5CkFnRUdDQ3FHU000OUF3RUhBMElBQkgySmVNUC9WQ254Z055dTI0TmhkMmY2YTNVOFFqeis3MUtQejlFek0waVgKMUQyVlVqMmlYQ1JHV09zZkl2OGhnM3Rnc1NkazhmVE8vanVhNTJFQjQxV2pnZ0VrTUlJQklEQU9CZ05WSFE4QgpBZjhFQkFNQ0JhQXdIUVlEVlIwbEJCWXdGQVlJS3dZQkJRVUhBd0lHQ0NzR0FRVUZCd01CTUF3R0ExVWRFd0VCCi93UUNNQUF3SFFZRFZSME9CQllFRkphWmFaYXZkSGhBaU12WlJrOCtmT3RrdGFJZk1COEdBMVVkSXdRWU1CYUEKRklVd1hUc3FjTlR0MVpKbkIvM3JPYlFhRGppbk1FUUdDQ3NHQVFVRkJ3RUJCRGd3TmpBMEJnZ3JCZ0VGQlFjdwpBWVlvYUhSMGNEb3ZMMjlqYzNBdVkyeHZkV1JtYkdGeVpTNWpiMjB2YjNKcFoybHVYMlZqWTE5allUQWRCZ05WCkhSRUVGakFVZ2drcUxqTXpOall1WjJHQ0J6TXpOall1WjJFd1BBWURWUjBmQkRVd016QXhvQytnTFlZcmFIUjAKY0RvdkwyTnliQzVqYkc5MVpHWnNZWEpsTG1OdmJTOXZjbWxuYVc1ZlpXTmpYMk5oTG1OeWJEQUtCZ2dxaGtqTwpQUVFEQWdOSEFEQkVBaUFGT1ArOUFYNy9hT2Z4dFV0anplRzRzeUZaRWZPQlFxQUFsL0Z6MmxUckpRSWdTdzZvCmkrdThPNDI4YXJMN1ArU2NwRzl4NXhQcmdOOHBMOVIzZUtGYUNxWT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQotLS0tLUJFR0lOIEFSR08gVFVOTkVMIFRPS0VOLS0tLS0KZXlKNmIyNWxTVVFpT2lKalpEWmlOREJqWldJeFpEWTVNV1V4WTJVMVpUUm1ZekEyWm1Wa05EQmtZeUlzSW1GagpZMjkxYm5SSlJDSTZJbVV5WWpJek56QmtZbVJqWmpZeE9HTmlaamRoTWpNeU5HUTVNemhtTVRBMUlpd2ljMlZ5CmRtbGpaVXRsZVNJNkluWXhMakF0Wm1ZMk1EaGpNbUUxT0dSak1qQTRaR1EyTVRRMVpUbGlMVE0wWlRCallXWmwKTnpaak1ERmlPVE5pWlRoallXTTNZMlV6TnpNMFpXVmtNVGt3TkdabVlqVXhZbU01WlRVM1ltSmlOV0UyWldObApNVGt5WWpnNE1qQmlZemN6TmpJd01HUm1NRFV6TWpneU9HUm1OR1V5WlRFek9EbGtPV1kxWmpJNVpEZ3pPREprCk56VXpaV0U1TmpVM1lUZzRPREJpTmpjNU9ERmpPVEl5WlRFeFl6aGpaVE16T0RkaE5ERTNORGRoWmprMk1tRmoKTlRFMFl6a3dNallpTENKaGNHbFViMnRsYmlJNkltVkVjVWxYYXpGT1prNVVXbGQzWlZSaGF6WlJUWGhVTm01cApRbXRQVWxwamRVTktkbEExT0d3aWZRPT0KLS0tLS1FTkQgQVJHTyBUVU5ORUwgVE9LRU4tLS0tLQ==
          EOD
          nohup cloudflared tunnel --origincert cert.pem --config config.yaml run > cf.log &
      - name: Connect Server
        run: |
          sleep 5.9h