name: wgetv2txt
on:
  workflow_dispatch:
  schedule:
    - cron: 30 8 * * *

jobs:
  env:
    runs-on: ubuntu-latest
    steps:
      - name: wgetv2
        run: |
          sudo apt update
          mkdir v2r
          cd v2r
          DATE=`date -d yesterday +%m%d`
          wget -O v2.txt https://raw.githubusercontent.com/pojiezhiyuanjun/freev2/master/$DATE.txt
          cat v2.txt > report.txt
      - name: Commit report
        run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'your-username@users.noreply.github.com'
          git commit -am "add--"
          git push
      - name: finshed
        run: |
          sleep 6m
